/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budgetmanager;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.DefaultListModel;

/**
 *
 * @author Wout
 */
public class Settings extends javax.swing.JFrame {
    private DefaultListModel dlm;
    private ManagerInterFace parent;

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        dlm = new DefaultListModel();
        listIncome.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnValid = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        panIncomes = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        spanIncomes = new javax.swing.JScrollPane();
        listIncome = new javax.swing.JList();
        panSavings = new javax.swing.JPanel();
        panWout = new javax.swing.JPanel();
        inSavEurWout = new javax.swing.JFormattedTextField();
        lblEurW = new javax.swing.JLabel();
        lblArsW = new javax.swing.JLabel();
        inSavArsWout = new javax.swing.JFormattedTextField();
        panAnita = new javax.swing.JPanel();
        inSavArsAnita = new javax.swing.JFormattedTextField();
        lblArsA = new javax.swing.JLabel();
        lblUsdA = new javax.swing.JLabel();
        inSavUsdAnita = new javax.swing.JFormattedTextField();
        panConv = new javax.swing.JPanel();
        lblEur2Ars = new javax.swing.JLabel();
        inEur2Ars = new javax.swing.JTextField();
        lblUsd2Ars = new javax.swing.JLabel();
        inUsd2Ars = new javax.swing.JTextField();
        lblEur2Usd = new javax.swing.JLabel();
        inEur2Usd = new javax.swing.JTextField();
        btnGetConv = new javax.swing.JButton();

        setTitle("Settings");
        setResizable(false);

        btnValid.setText("Validate");

        BtnCancel.setText("Cancel");

        panIncomes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Incomes"));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIncome(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteIncome(evt);
            }
        });

        spanIncomes.setViewportView(listIncome);

        javax.swing.GroupLayout panIncomesLayout = new javax.swing.GroupLayout(panIncomes);
        panIncomes.setLayout(panIncomesLayout);
        panIncomesLayout.setHorizontalGroup(
            panIncomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panIncomesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panIncomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panIncomesLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDel))
                    .addComponent(spanIncomes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panIncomesLayout.setVerticalGroup(
            panIncomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panIncomesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spanIncomes, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panIncomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDel))
                .addContainerGap())
        );

        panSavings.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Initial Savings"));

        panWout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Wout"));

        inSavEurWout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        inSavEurWout.setText("0.00");

        lblEurW.setText("EUR");

        lblArsW.setText("ARS");

        inSavArsWout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        inSavArsWout.setText("0.00");

        javax.swing.GroupLayout panWoutLayout = new javax.swing.GroupLayout(panWout);
        panWout.setLayout(panWoutLayout);
        panWoutLayout.setHorizontalGroup(
            panWoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panWoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panWoutLayout.createSequentialGroup()
                        .addComponent(lblEurW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inSavEurWout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panWoutLayout.createSequentialGroup()
                        .addComponent(lblArsW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inSavArsWout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panWoutLayout.setVerticalGroup(
            panWoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWoutLayout.createSequentialGroup()
                .addGroup(panWoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSavEurWout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEurW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panWoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArsW)
                    .addComponent(inSavArsWout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        panAnita.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Anita"));

        inSavArsAnita.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        inSavArsAnita.setText("0.00");

        lblArsA.setText("ARS");

        lblUsdA.setText("USD");

        inSavUsdAnita.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        inSavUsdAnita.setText("0.00");

        javax.swing.GroupLayout panAnitaLayout = new javax.swing.GroupLayout(panAnita);
        panAnita.setLayout(panAnitaLayout);
        panAnitaLayout.setHorizontalGroup(
            panAnitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAnitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAnitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panAnitaLayout.createSequentialGroup()
                        .addComponent(lblUsdA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inSavUsdAnita, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAnitaLayout.createSequentialGroup()
                        .addComponent(lblArsA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inSavArsAnita)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAnitaLayout.setVerticalGroup(
            panAnitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAnitaLayout.createSequentialGroup()
                .addGroup(panAnitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSavUsdAnita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsdA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panAnitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArsA)
                    .addComponent(inSavArsAnita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panSavingsLayout = new javax.swing.GroupLayout(panSavings);
        panSavings.setLayout(panSavingsLayout);
        panSavingsLayout.setHorizontalGroup(
            panSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panAnita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panSavingsLayout.createSequentialGroup()
                        .addComponent(panWout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panSavingsLayout.setVerticalGroup(
            panSavingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSavingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panWout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panAnita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panConv.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Conversion"));

        lblEur2Ars.setText("EUR to ARS");

        inEur2Ars.setText("1.00");

        lblUsd2Ars.setText("USD to ARS");

        inUsd2Ars.setText("1.00");

        lblEur2Usd.setText("EUR to USD");

        inEur2Usd.setText("1.00");

        btnGetConv.setText("Get Online");
        btnGetConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getOnlineConv(evt);
            }
        });

        javax.swing.GroupLayout panConvLayout = new javax.swing.GroupLayout(panConv);
        panConv.setLayout(panConvLayout);
        panConvLayout.setHorizontalGroup(
            panConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inEur2Ars)
                    .addComponent(inUsd2Ars)
                    .addComponent(inEur2Usd)
                    .addGroup(panConvLayout.createSequentialGroup()
                        .addGroup(panConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEur2Ars)
                            .addComponent(lblUsd2Ars)
                            .addComponent(lblEur2Usd))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConvLayout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addComponent(btnGetConv)))
                .addContainerGap())
        );
        panConvLayout.setVerticalGroup(
            panConvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEur2Ars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inEur2Ars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUsd2Ars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inUsd2Ars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEur2Usd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inEur2Usd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGetConv)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panIncomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panConv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panIncomes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panSavings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panConv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCancel)
                    .addComponent(btnValid))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddIncome(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIncome
        AddingIncome ai = new AddingIncome();
        ai.setVisible(true);
        ai.setParent(this);
    }//GEN-LAST:event_AddIncome

    private void DeleteIncome(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteIncome
        if(listIncome.getSelectedIndex() > -1)
            dlm.removeElementAt(listIncome.getSelectedIndex());
    }//GEN-LAST:event_DeleteIncome

    private void getOnlineConv(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOnlineConv
        putConv(true);
    }//GEN-LAST:event_getOnlineConv

    public void AddToList(String who, String cur, String amnt)
    {
       dlm.addElement(cur+" "+amnt+" ("+who+")");
    }
    
    public void setParent(ManagerInterFace mif)
    {
        parent = mif;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }
    
    public void putConv(boolean renew)
    {
        if(renew)
        {
            parent.getConv("ARS", true);
        }
        double c = parent.getConv("ARS", false) / parent.getConv("EUR", false);
        inEur2Ars.setText(String.valueOf(c));
        inUsd2Ars.setText(String.valueOf(parent.getConv("ARS", false)));
        inEur2Usd.setText(String.valueOf(1 / parent.getConv("EUR", false)));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnGetConv;
    private javax.swing.JButton btnValid;
    private javax.swing.JTextField inEur2Ars;
    private javax.swing.JTextField inEur2Usd;
    private javax.swing.JFormattedTextField inSavArsAnita;
    private javax.swing.JFormattedTextField inSavArsWout;
    private javax.swing.JFormattedTextField inSavEurWout;
    private javax.swing.JFormattedTextField inSavUsdAnita;
    private javax.swing.JTextField inUsd2Ars;
    private javax.swing.JLabel lblArsA;
    private javax.swing.JLabel lblArsW;
    private javax.swing.JLabel lblEur2Ars;
    private javax.swing.JLabel lblEur2Usd;
    private javax.swing.JLabel lblEurW;
    private javax.swing.JLabel lblUsd2Ars;
    private javax.swing.JLabel lblUsdA;
    private javax.swing.JList listIncome;
    private javax.swing.JPanel panAnita;
    private javax.swing.JPanel panConv;
    private javax.swing.JPanel panIncomes;
    private javax.swing.JPanel panSavings;
    private javax.swing.JPanel panWout;
    private javax.swing.JScrollPane spanIncomes;
    // End of variables declaration//GEN-END:variables
}
